### PR TITLE
adding instructions on setting up geonames for every project

### PR DESCRIPTION
**Pull request by jenlindner**

### CODE REVIEW

**Comment by jenlindner** [comment]
We need to confirm the user name for the dce testing account nurax employs and document it here.

**Comment by jenlindner** [comment]
Hi @bess, sure. This is intended for development only, although augmenting later with the production instructions would be great. And @mark-dce says we do have Geonames testing credentials, which I'd be happy to update the docs with.

**Comment by mark-dce** [comment]
Actually, the genomes credentials on nurax are specific to that project, so we should probably set up an account for us to use in demo and sandbox environments.

**Comment by jenlindner** [comment]
Okay, I have one called dce_tester created and registered, but we need a dce testing email account for it (it's registered to my dce email now, so we need to change that). Do we have a dce_testing email account?

**Pull request merged**
